routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



/**
 * Public Viewing Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('/','WelcomeController@index');
Route::view('about', 'about');
Route::view('services', 'services');
Route::view('my-favorite', 'tenant.my-favorite');
Route::view('faq', 'faq');


/**
 * Contact Us  Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('/contact-us', 'ContactsController@index');
Route::post('/contact-us', 'ContactsController@store');


// Route::view('blog','blog');

// Route::view('blog-details','blog-full');


/**
 * Password Reset Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('settings-password', 'SettingsController@index');
Route::patch('settings-password', 'SettingsController@update');

Route::get('my-properties', 'UserPropertiesController@index')->name('my-properties');


/**
 * Roles Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('role', 'RoleController@index');
Route::post('role', 'RoleController@store');

/**
 * Property Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('property', 'PropertyController@index');
Route::post('property', 'PropertyController@store');
Route::get('property/create', 'PropertyController@create');
Route::get('property/{id}/edit', 'PropertyController@edit');
Route::get('property/{slug}', 'PropertyController@show');
Route::patch('property/{slug}', 'PropertyController@update');
Route::delete('property/{id}', 'PropertyController@destroy');

/**
 * Property Photos Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::post('photo/{slug}/files', 'PropertyController@addPhoto');
Route::get('photo/{slug}', 'PropertyPhotoController@show');
Route::delete('photo/{slug}', 'PropertyPhotoController@destroy');


/**
 * Agents Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('agent', 'AgentProfileController');
Route::get('agent-settings', 'ProfilePictureController@index');


/**
 * Admin Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('admin', 'AdminController@index');
Route::get('all-admins', 'AdminController@allAdmins');
Route::get('admin/create', 'AdminController@create');
Route::post('admin/{admin}', 'AdminController@store');
Route::post('admin-profile', 'AdminProfileController@store');
Route::get('admin-properties', 'AdminAllPropertiesController');
Route::get('admin-settings', 'AdminSettingsController');
Route::post('admin-settings', 'AdminSettingsController@store');
Route::get('all-agents', 'AllAgentsController');
Route::get('all-tenants', 'AllTenantsController');
Route::get('all-landlords', 'AllLandlordController');
Route::get('list-blogs', 'AllBlogsController');

/**
 * LandLord Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('landlord', 'LandlordProfileController');
Route::get('landlord-settings', 'LandlordProfilePictureController@index');
Route::post('landlord-settings', 'LandlordProfilePictureController@store');
Route::get('/landlord-properties', 'LandLordPropertiesController@index');

/**
 * Tenants Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('tenant', 'TenantProfileController');
Route::get('tenant-settings', 'TenantProfilePictureController@index');


Route::get('my-tenants', 'RentedPropertyController@index');
Route::delete('/profile-picture/{id}', 'ProfilePictureController@destroy');
Route::post('/profile-picture', 'ProfilePictureController@store');

/**
 * Blog Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('blogs', 'BlogController');
Route::get('blog/{slug}/images', 'BlogImageController@create')->middleware('admin');
Route::post('blog-images/{slug}/files', 'BlogController@addImage')->middleware('admin');
Route::delete('blog-image/{blog}/', 'BlogImageController@destroy')->middleware('admin');
Route::post('blog/{blog}/comments', 'BlogCommentsController@store');
Route::post('comments/{comment}/reply', 'CommentsReplyController@store')->middleware('admin');
Route::patch('comments/{comment}/reply', 'CommentsReplyController@update')->middleware('admin');
Route::get('comments/{comment}', 'CommentsReplyController@index');
Route::get('blog/show', 'BlogController@show'); // This is a temporary route




/**
 * Payment Routes Groups
 * ----------------------------------------------------------------------------------------->
 */
Route::get('payments', 'MyPaymentController@index');
Route::get('rental/{slug}', 'RentalController@index');
Route::post('tujenge', 'TujengepayController@savedata');
Route::get('wallet', 'WalletController@index');
Route::get('status', 'WalletController@status');
Route::post('wallet', 'WalletController@walletToMpesa');
Route::get('balance', 'WalletToBankController@balance');
Route::get('transaction-query', 'WalletController@transactionsQuery'); //Mpesa
Route::get('ministatement', 'MinistatementController@ministatement');
Route::get('wallet-to-bank', 'WalletToBankController@index');
Route::post('wallet-to-bank', 'WalletToBankController@walletToBank');
Route::get('transaction-query-bank', 'WalletToBankTransanctionQueryController@transactionBankQuery'); //Bank
Route::post('collection', 'CollectionController@interswitchCollection'); //collection
Route::get('card', 'CollectionController@card'); //collection



//password Ngi!956ozeh

/**
 * Socialite Authentication Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('redirect/{provider}', 'SocialController@redirect');
Route::get('callback/{provider}', 'SocialController@callback');
Route::get('logout', 'Auth\LoginController@logout');

Auth::routes();

app/Blog.php
<?php

namespace App;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Blog extends Model
{
    use Sluggable, Uuids, HasFactory;

    protected $casts = ['id' => 'string'];

    protected $fillable = [
        'description',
        'title',
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function sluggable() :array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function path()
    {
        return '/blog/'.$this->slug;
    }

    public function photos()
    {
        return $this->hasMany(BlogImage::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function getFormattedTitleAttribute()
    {
        return Str::limit($this->title, 15);
    }

    public function formattedDate()
    {
        return $this->created_at->format('M d');
    }
    public function formattedDay()
    {
        return $this->created_at->format('d');
    }
    public function formattedMonth()
    {
        return $this->created_at->format('M');
    }

    public function blogDescription(): string
    {
        return Str::limit($this->description, 150, '..');
    }

    public function getExcerptAttribute(): string
    {
        return Str::limit($this->description, 75, '...');
    }


    public static function locatedAt($slug)
    {
        return static::where(compact('slug'))->firstOrFail();
    }

    public function addPhoto(BlogImage $blogImages)
    {
        return $this->photos()->save($blogImages);
    }
}

resources/views/admin/admin-menu.blade.php
<!--header -->
<div class="header clearfix">
	<h2>{{auth()->user()->name}}</h2>
	<h4>CloudKey Admin</h4>
	<img src="{{auth()->user()->avatar == true ? '/uploaded/avatars/'.auth()->user()->avatar  : '/assets/img/avatar/avatar-13.jpg' }}" alt="avatar" class="img-fluid profile-img">
</div>
<!-- Detail -->
<div class="detail clearfix">
	<ul>
		<li>
			<a href="{{url('/', auth()->user()->roles->role ) }}" class="active">
				<i class="flaticon-user"></i>Profile
			</a>
		</li>
		<li>
			<a href="/admin-properties">
				<i class="flaticon-house"></i>Properties List
			</a>
		</li>
		<li>
			<a href="/property/create">
				<i class="fa fa-plus"></i>Submit a Property
			</a>
		</li>
		<li>
			<a href="/all-admins	">
				<i class="fa fa-users"></i>Admins List
			</a>
		</li>
		<li>
			<a href="/all-agents">
				<i class="fa fa-users"></i>Agents List
			</a>
		</li>
		<li>
			<a href="/all-landlords">
				<i class="fa fa-users"></i>Landlords List
			</a>
		</li>
		<li>
			<a href="/all-tenants">
				<i class="fa fa-users"></i>Tenants List
			</a>
		</li>
		<li>
			<a href="#">
				<i class="flaticon-money-bag-with-dollar-symbol"></i>Revenue Collected
			</a>
		</li>
		<li>
			<a href="/admin/create">
				<i class="fa fa-plus"></i>Add Admin
			</a>
		</li>
		<li>
			<a href="/list-blogs">
				<i class="fa fa-rss"></i>List Blogs
			</a>
		</li>
		<li>
			<a href="/blogs">
				<i class="fa fa-file"></i>Blogs
			</a>
		</li>
		<li>
			<a href="/blogs/create">
				<i class="fa fa-plus"></i>Add Blog
			</a>
		</li>
		<li>
			<a href="/admin-settings">
				<i class="fa fa-cog"></i>Settings
			</a>
		</li>
		<li>
			<a href="{{ route('logout') }}" onclick="event.preventDefault();  document.getElementById('logout-form').submit();" >
				<i class="flaticon-logout"></i>Log Out
			</a>
			<form id="logout-form" action="{{route('logout')}}" method="POST" style="display: none;">
				@csrf
			</form>
		</li>
	</ul>
</div>

resources/views/admin/admin-profile.blade.php
<div class="col-lg-8 col-md-7 col-sm-12">
	<div class="my-address contact-1 widget">
		<h3 class="heading">Personal Details</h3>
		@include('partials.errors')
		@if(Session::has('updated-profile'))
		<div class="alert alert-success">
			{{ Session::get('updated-profile') }}
		</div>
		@endif
		<form action="/admin-profile" method="post">
			@csrf
			<div class="row">
				<div class="col-lg-12">
					<div class="form-group email">
						<label>Full Name</label>
						<input type="text" name="name" class="form-control" placeholder="Full Name"
						value="{{ old('name', $user->name) }}" required>
					</div>
				</div>
				<div class="col-lg-12 ">
					<div class="form-group subject">
						<label>Email Address</label>
						<input type="text" name="email" class="form-control"
						placeholder="Email Addeess"
						value="{{ old('email',$user->email) }}" required>
					</div>
				</div>
				<div class="col-lg-12">
					<div class="send-btn">
						<button type="submit" class="text-white btn btn-color btn-md btn-message">Save the Changes</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

resources/views/admin/agents.blade.php
@extends('admin.main')

@section('details')

    @include('partials.user_banner', ['type' => 'My Agents'])

    <div class="user-page content-area-13">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-5 col-sm-12">
                    <div class="user-profile-box mrb">
                        <!--header -->
                        @include('admin.admin-menu')
                    </div>
                </div>
                <div class="col-lg-8 col-md-7 col-sm-12">
                    @if(Session::has('deleted-property'))
                        <div class="alert alert-success">
                            {{ Session::get('deleted-property') }}
                        </div>
                    @endif
                    @if(count($agents))
                        <div class="my-properties">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Type</th>
                                    <th>Listed Properties</th>
                                    <th>Date Listed</th>
                                    <th>Approved</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                @foreach( $agents as $agent )
                                    <tbody>
                                    <tr>
                                        <td>{{ $agent->user()->first()->name }}</td>
                                        <td>{{ ucfirst($agent->user()->first()->properties()->first()->type) ?? html_entity_decode('&mdash;') }}</td>
                                        <td>{{ $agent->user()->first()->properties()->count() }}</td>
                                        <td>{{$agent->created_at->diffForHumans()}}</td>
                                        <td>Yes</td>
                                        <td><button class="btn btn-dark"><span class="text-sm">disapprove</span></button></td>
                                    </tr>
                                    </tbody>
                                @endforeach
                            </table>
                        </div>
                        <div class="pagination-box">
                            {{  $agents->links('partials.pagination') }}
                        </div>
                    @else
                        <div class="my-address contact-2 widget hdn-mb-30">
                            <h3 class="heading">My Agents</h3>
                            <label>You don't have Agents yet</label>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/all-admins.blade.php
@extends('admin.main')

@section('details')

    @include('partials.user_banner', ['type' => 'Admins'])

    <div class="user-page content-area-13">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-5 col-sm-12">
                    <div class="user-profile-box mrb">
                        <!--header -->
                        @include('admin.admin-menu')
                    </div>
                </div>
                <div class="col-lg-8 col-md-7 col-sm-12">
                    @if(Session::has('deleted-admin'))
                        <div class="alert alert-success">
                            {{ Session::get('deleted-admin') }}
                        </div>
                    @endif
                    @if(count($admins))
                        <div class="my-properties">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Created At</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                @foreach( $admins as $role )
                                    <tbody>
                                    <tr>
                                        <td>
                                            {{ $role->user->name }}
                                        </td>
                                        <td>{{ $role->user->email }}</td>
                                        <td>{{$role->user->created_at->diffForHumans()}}</td>
                                        @unless (auth()->id() === $role->user->id)
                                        <td>
                                            Delete
                                        </td>
                                        @endunless
                                    </tr>
                                    </tbody>
                                @endforeach
                            </table>
                        </div>
                        <div class="pagination-box">
                            {{ $admins->links('partials.pagination') }}
                        </div>
                    @else
                        <div class="my-address contact-2 widget hdn-mb-30">
                            <h3 class="heading">My Agents</h3>
                            <label>You don't have Agents yet</label>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/all_blogs.blade.php
@extends('admin.main')

@section('details')

@include('partials.user_banner', ['type' => 'All Blogs'])

<div class="user-page content-area-2">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-12 col-sm-12">
				<div class="user-profile-box mrb">
					@include('admin.admin-menu')
				</div>
			</div>
			<div class="col-lg-8 col-md-12 col-sm-12">
				@if(Session::has('deleted-blog'))
				<div class="alert alert-info">
					{{ Session::get('deleted-blog') }}
				</div>
				@endif
				@if(count($blogs))
				<div class="my-properties">
					<table class="table">
						<thead>
							<tr>
								<th>Blog Image</th>
								<th>Title</th>
								<th>Description</th>
								<th>Created</th>
								<th>Actions</th>
							</tr>
						</thead>
						@foreach( $blogs as $blog )
						<tbody>
							<tr>
								<td class="image">
									<a href="/property/{{$blog->slug}}">
										@foreach($blog->photos->chunk(1) as $set)
											@foreach($set as $photo)
												@if ($loop->parent->first)
													<img class="img-fluid" src="/{{$photo->path}}" alt="blog">
												@endif
											@endforeach
										@endforeach
									</a>
								</td>
								<td>
									<div class="inner">
										<a href="/blog/{{$blog->slug}}"><h2>{{ $blog->title }}</h2></a>
									</div>
								</td>
								<td>{{ $blog->excerpt }}</td>
								<td>{{ $blog->created_at->diffForHUmans(null, false) }}</td>
								<td class="actions flex items-center">
									<a href="{{ route('blogs.edit', $blog)}}" class="edit" title="Edit"><i class="fa fa-pencil pt-2"></i></a>
									<form action="{{ route('blogs.destroy', $blog)}}" method="post" title="Delete">
										@csrf
										@method('delete')
										<button class="btn btn-light" type="submit"><i class="delete fa fa-trash-o"></i></button>
									</form>
								</td>
							</tr>
						</tbody>
						@endforeach
					</table>
				</div>
				<div class="pagination-box">
					{{ $blogs->links('partials.pagination') }}
				</div>
				@else
				<div class="my-address contact-2 widget hdn-mb-30">
					<h3 class="heading">All Blogs</h3>
					<label>You Don't have Blogs yet</label>
				</div>
				@endif
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/create.blade.php
@extends('admin.main')

@section('details')

    @include('partials.user_banner', ['type' => 'Add Admin'])

    <div class="user-page content-area-13">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-5 col-sm-12">
                    <div class="user-profile-box mrb">
                        <!--header -->
                        @include('admin.admin-menu')
                    </div>
                </div>
                <add-admin></add-admin>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/index.blade.php
@extends('admin.main')

@section('details')

    @include('partials.user_banner', ['type' => 'Admin Profile',])

    <!-- User page start -->
    <div class="user-page content-area-14">
        <div class="container">
            <div class="row search-area contact-1">
                <div class="col-lg-4 col-md-5 col-sm-12">
                    <div class="user-profile-box mrb">
                        @include('admin.admin-menu')
                    </div>
                </div>
               @include('admin.admin-profile')
            </div>
        </div>
    </div>
    <!-- User page end -->


@endsection

resources/views/admin/landlords.blade.php
@extends('admin.main')

@section('details')

    @include('partials.user_banner', ['type' => 'My Landlords'])

    <div class="user-page content-area-13">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-5 col-sm-12">
                    <div class="user-profile-box mrb">
                        <!--header -->
                        @include('admin.admin-menu')
                    </div>
                </div>
                <div class="col-lg-8 col-md-7 col-sm-12">
                    @if(Session::has('deleted-property'))
                        <div class="alert alert-success">
                            {{ Session::get('deleted-property') }}
                        </div>
                    @endif
                    @if(count($landlords))
                        <div class="my-properties">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Property Name</th>
                                    <th>Listed Properties</th>
                                    <th>Approved</th>
                                    <th>Date Listed</th>
                                    <th>Type</th>
                                </tr>
                                </thead>
                                @foreach( $landlords as $user )
                                    <tbody>
                                    <tr>
                                        <td>
                                            {{ $user->user->name }}
                                        </td>
                                        <td>{{ $user->user->properties()->first()->title ?? html_entity_decode('&mdash;') }}</td>
                                        <td>Yes</td>
                                        <td>{{$user->created_at->diffForHumans()}}</td>
                                        <td>{{ $user->user->properties()->first()->type ??  html_entity_decode('&mdash;') }}</td>
                                        <td>Apartment</td>
                                    </tr>
                                    </tbody>
                                @endforeach
                            </table>
                        </div>
                        <div class="pagination-box">
                            {{ $landlords->links('partials.pagination')}}
                        </div>
                    @else
                        <div class="my-address contact-2 widget hdn-mb-30">
                            <h3 class="heading">All Landlords</h3>
                            <label>You don't have Landlords yet</label>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/main.blade.php
@extends('layouts.app')

@section('content')

    @include('partials.header')

    @yield('details')

    @include('partials.footer')

@endsection

resources/views/admin/properties.blade.php
@extends('admin.main')

@section('details')

@include('partials.user_banner', ['type' => 'All Properties'])

<div class="user-page content-area-2">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-12 col-sm-12">
				<div class="user-profile-box mrb">
					@include('admin.admin-menu')
				</div>
			</div>
			<div class="col-lg-8 col-md-12 col-sm-12">
				@if(Session::has('deleted-property'))
				<div class="alert alert-success">
					{{ Session::get('deleted-property') }}
				</div>
				@endif
				@if(count($properties))
				<div class="my-properties">
					<table class="table">
						<thead>
							<tr>
								<th>Property</th>
								<th></th>
								<th>Created</th>
								<th>Views</th>
								<th>Actions</th>
							</tr>
						</thead>
						@foreach( $properties as $property )
						<tbody>
							<tr>
								<td class="image">
									<a href="/property/{{$property->slug}}">
										<x-image :property="$property" class="img-fluid"></x-image>
									</a>
								</td>
								<td>
									<div class="inner">
										<a href="/property/{{$property->slug}}"><h2>{{$property->truncatedTitle()}}</h2></a>
										<figure><i class="flaticon-facebook-placeholder-for-locate-places-on-maps"></i>
											<small>{{$property->address}} </small>
										</figure>
										<div class="tag price">Ksh. {{$property->price}}</div>
									</div>
								</td>
								<td>{{$property->created_at }}</td>
								<td>421</td>
								<td class="actions flex items-center">
									<a href="/property/{{$property->id}}/edit" class="edit" title="Edit"><i class="fa fa-pencil pt-2"></i></a>
									<form action="/property/{{ $property->id}}" method="post" title="Delete">
										@csrf
										@method('delete')
										<button class="btn btn-light" type="submit"><i class="delete fa fa-trash-o"></i></button>
									</form>
								</td>
							</tr>
						</tbody>
						@endforeach
					</table>
				</div>
				<div class="pagination-box">
					{{ $properties->links('partials.pagination') }}
				</div>
				@else
				<div class="my-address contact-2 widget hdn-mb-30">
					<h3 class="heading">All Properties</h3>
					<label>You Don't have Properties yet</label>
				</div>
				@endif
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/revenue.blade.php
@extends('admin.main')

@section('details')

    @include('partials.user_banner', ['type' => 'All Payments'])

    <div class="user-page content-area-2">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="user-profile-box mrb">
                        @include('landlord.landlord-menu')
                    </div>
                </div>
                <div class="col-lg-8 col-md-12 col-sm-12">
                    <div class="my-properties">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Property Name</th>
                                <th>Amount Payed</th>
                                <th>Balance</th>
                                <th>Payment Date</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>
                                    <a href="#"><h2>Modern Family Home</h2></a>
                                </td>
                                <td>
                                    <div class="inner">
                                        <div class="tag priKsh.e">Ksh. 27,000</div>
                                    </div>
                                </td>
                                <td>421</td>
                                <td>14.02.2018</td>

                            </tr>
                            <tr>
                                <td>
                                    <a href="#"><h2>Modern Family Home</h2></a>
                                </td>
                                <td>
                                    <div class="inner">
                                        <div class="tag price">Ksh. 315,000</div>
                                    </div>
                                </td>
                                <td>266</td>
                                <td>4.01.2018</td>

                            </tr>
                            <tr>
                                <td>
                                    <a href="#"><h2>Modern Family Home</h2></a>
                                </td>
                                <td>
                                    <div class="inner">
                                        <div class="tag price">Ksh. 62,000</div>
                                    </div>
                                </td>
                                <td>45</td>
                                <td>24.03.2018</td>

                            </tr>
                            <tr>
                                <td>
                                    <a href="#"><h2>Modern Family Home</h2></a>
                                </td>
                                <td>
                                    <div class="inner">
                                        <div class="tag price">Ksh. 27,000</div>
                                    </div>
                                </td>
                                <td>421</td>
                                <td>14.02.2018</td>

                            </tr>
                            <tr>
                                <td>
                                    <a href="#"><h2>Modern Family Home</h2></a>
                                </td>
                                <td>
                                    <div class="inner">
                                        <div class="tag price">Ksh. 315,000</div>
                                    </div>
                                </td>
                                <td>266</td>
                                <td>4.01.2018</td>

                            </tr>
                            <tr>
                                <td class="#">
                                    <a href="#"><h2>Modern Family Home</h2></a>
                                </td>
                                <td>
                                    <div class="inner">
                                        <div class="tag price">Ksh. 62,000</div>
                                    </div>
                                </td>
                                <td>45</td>
                                <td>24.03.2018</td>

                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="pagination-box">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination">
                                <li class="page-item"><a class="page-link" href="#"><span aria-hidden="true">«</span></a></li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#"><span aria-hidden="true">»</span></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection