routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



/**
 * Public Viewing Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('/','WelcomeController@index');
Route::view('about', 'about');
Route::view('services', 'services');
Route::view('my-favorite', 'tenant.my-favorite');
Route::view('faq', 'faq');


/**
 * Contact Us  Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('/contact-us', 'ContactsController@index');
Route::post('/contact-us', 'ContactsController@store');


// Route::view('blog','blog');

// Route::view('blog-details','blog-full');


/**
 * Password Reset Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('settings-password', 'SettingsController@index');
Route::patch('settings-password', 'SettingsController@update');

Route::get('my-properties', 'UserPropertiesController@index')->name('my-properties');


/**
 * Roles Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('role', 'RoleController@index');
Route::post('role', 'RoleController@store');

/**
 * Property Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('property', 'PropertyController@index');
Route::post('property', 'PropertyController@store');
Route::get('property/create', 'PropertyController@create');
Route::get('property/{id}/edit', 'PropertyController@edit');
Route::get('property/{slug}', 'PropertyController@show');
Route::patch('property/{slug}', 'PropertyController@update');
Route::delete('property/{id}', 'PropertyController@destroy');

/**
 * Property Photos Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::post('photo/{slug}/files', 'PropertyController@addPhoto');
Route::get('photo/{slug}', 'PropertyPhotoController@show');
Route::delete('photo/{slug}', 'PropertyPhotoController@destroy');


/**
 * Agents Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('agent', 'AgentProfileController');
Route::get('agent-settings', 'ProfilePictureController@index');


/**
 * Admin Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('admin', 'AdminController@index');
Route::get('all-admins', 'AdminController@allAdmins');
Route::get('admin/create', 'AdminController@create');
Route::post('admin/{admin}', 'AdminController@store');
Route::post('admin-profile', 'AdminProfileController@store');
Route::get('admin-properties', 'AdminAllPropertiesController');
Route::get('admin-settings', 'AdminSettingsController');
Route::post('admin-settings', 'AdminSettingsController@store');
Route::get('all-agents', 'AllAgentsController');
Route::get('all-tenants', 'AllTenantsController');
Route::get('all-landlords', 'AllLandlordController');
Route::get('list-blogs', 'AllBlogsController');

/**
 * LandLord Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('landlord', 'LandlordProfileController');
Route::get('landlord-settings', 'LandlordProfilePictureController@index');
Route::post('landlord-settings', 'LandlordProfilePictureController@store');
Route::get('/landlord-properties', 'LandLordPropertiesController@index');

/**
 * Tenants Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('tenant', 'TenantProfileController');
Route::get('tenant-settings', 'TenantProfilePictureController@index');


Route::get('my-tenants', 'RentedPropertyController@index');
Route::delete('/profile-picture/{id}', 'ProfilePictureController@destroy');
Route::post('/profile-picture', 'ProfilePictureController@store');

/**
 * Blog Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('blogs', 'BlogController');
Route::get('blog/{slug}/images', 'BlogImageController@create')->middleware('admin');
Route::post('blog-images/{slug}/files', 'BlogController@addImage')->middleware('admin');
Route::delete('blog-image/{blog}/', 'BlogImageController@destroy')->middleware('admin');
Route::post('blog/{blog}/comments', 'BlogCommentsController@store');
Route::post('comments/{comment}/reply', 'CommentsReplyController@store')->middleware('admin');
Route::patch('comments/{comment}/reply', 'CommentsReplyController@update')->middleware('admin');
Route::get('comments/{comment}', 'CommentsReplyController@index');
Route::get('blog/show', 'BlogController@show'); // This is a temporary route




/**
 * Payment Routes Groups
 * ----------------------------------------------------------------------------------------->
 */
Route::get('payments', 'MyPaymentController@index');
Route::get('rental/{slug}', 'RentalController@index');
Route::post('tujenge', 'TujengepayController@savedata');
Route::get('wallet', 'WalletController@index');
Route::get('status', 'WalletController@status');
Route::post('wallet', 'WalletController@walletToMpesa');
Route::get('balance', 'WalletToBankController@balance');
Route::get('transaction-query', 'WalletController@transactionsQuery'); //Mpesa
Route::get('ministatement', 'MinistatementController@ministatement');
Route::get('wallet-to-bank', 'WalletToBankController@index');
Route::post('wallet-to-bank', 'WalletToBankController@walletToBank');
Route::get('transaction-query-bank', 'WalletToBankTransanctionQueryController@transactionBankQuery'); //Bank
Route::post('collection', 'CollectionController@interswitchCollection'); //collection
Route::get('card', 'CollectionController@card'); //collection



//password Ngi!956ozeh

/**
 * Socialite Authentication Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('redirect/{provider}', 'SocialController@redirect');
Route::get('callback/{provider}', 'SocialController@callback');
Route::get('logout', 'Auth\LoginController@logout');

Auth::routes();

app/Property.php
<?php

namespace App;

use App\Uuids;
use Carbon\Carbon;
use App\Utilities\Counties;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Property extends Model
{
    use Sluggable,Uuids,HasFactory;

    protected $fillable = [
        'user_id',
        'title',
        'type',
        'price',
        'deposit',
        'area',
        'bedroom',
        'bathroom',
        'address',
        'county',
        'town',
        'description',
        'units',
        'postal_code',
        'available_date',
        'compound_units',
        'installments',
        'features',
        'service_charge'
    ];
    
    protected $casts = [
        'id' => 'string',
        'features' => 'array',
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function photos()
    {
        return $this->hasMany(PropertyPhoto::class, 'property_id');
    }

    public static function locatedAt($slug)
    {
        return static::where(compact('slug'))->firstOrFail();
    }

    public function addPhoto(PropertyPhoto $propertyPhoto)
    {
        return $this->photos()->save($propertyPhoto);
    }

    public function path()
    {
        return '/photo/' . $this->slug;
    }

    public function getCreatedAtAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d-m-Y');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function createdDate()
    {
        return Carbon::parse($this->created_at)->diffForHumans();
    }


    public function price_format(): string
    {
        return number_format($this->price);
    }

    public function deposit_format(): string
    {
        return number_format($this->deposit);
    }

    public function total()
    {
        return $this->price + $this->deposit;
    }

    public function fullAmount()
    {
        $total = $this->price + $this->deposit;

        return number_format($total);
    }

    public function installment(): string
    {
        return number_format($this->deposit * 0.5);
    }

    public function rentalAndInstallment(): string
    {
        return number_format($this->price + $this->deposit * 0.5);
    }

    public function truncatedTitle(): string
    {
        return Str::limit($this->title, 27, '...');
    }

    public function truncatedTitleRecent(): string
    {
        return Str::limit($this->title, 15, '...');
    }

    public function truncatedDescriptionRecent(): string
    {
        return Str::limit($this->title, 60, '...');
    }

    public function truncatedTitleWidget(): string
    {
        return Str::limit($this->title, 15, '...');
    }

    public function truncatedDescription(): string
    {
       return Str::limit($this->description, 70, '...');
    }

    public function getformattedDateAttribute(): string
    {
        return  Carbon::parse($this->created_at)->format('F j, Y');
    }

    public function getformattedCreatedAtAttribute()
    {
        return  Carbon::parse($this->created_at)->diffForHumans();
    }

    public function counties(): array
    {
        return Counties::all();
    }

}

app/Http/Controllers/PropertyController.php
<?php

namespace App\Http\Controllers;


use App\Property;
use App\PropertyPhoto;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\PropertyRequest;
use Symfony\Component\HttpFoundation\File\UploadedFile;


class PropertyController extends Controller
{
     public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }


    public function index()
    {
         $user = Auth::user();

        return view('properties.index', compact( 'user'));
    }


    public function create(Property $property)
    {
       return view('properties.create', compact('property'));
    }


    public function store(Property $property, PropertyRequest $request)
    {
        $property = new Property($request->all());

        Auth::user()->properties()->save($property);

        return redirect($property->path());
    }

    public function addPhoto(Request $request, $slug)
    {

        $this->validate($request, ['file' => 'required|mimes:jpg,jpeg,png,bmp,webp']);

        $propertyPhoto = $this->makePhoto($request->file('file'));

        Property::locatedAt($slug)->addPhoto($propertyPhoto);

    }

    protected function makePhoto(UploadedFile $file)
    {
        return PropertyPhoto::named($file->getClientOriginalName())->move($file);
    }


    public function show(Property $property, $slug)
    {
         $property = Property::locatedAt($slug)->load('photos:id,thumbnail_path,path,property_id');

         return view('properties.show', compact('property'));
    }


    public function edit(Request $request, Property $property, $id)
    {
        $property = Property::findOrFail($id);

        return view('properties.edit', compact('property'));
    }


    public function update(PropertyRequest $request, $slug)
    {
        $property = Property::findOrFail($slug);

        $property->update($request->all());

        return redirect($property->path())->with('You have successfully updated the Property');
    }


    public function destroy($slug)
    {
        Property::findOrFail($slug)->delete();

        return back()->with('deleted-property', 'You have removed a property from listing');
    }

}

resources/views/properties/create.blade.php
@extends('layouts.app')

@section('content')

   @include('partials.header')

   <!-- Sub banner 2 start -->

    @include('partials.banner', ['title' => 'Submit Property', 'type' =>'Submit Property' ])

    <!-- Sub banner 2 end -->

    <!-- User page start -->
    <div class="user-page content-area-7">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="search-area contact-1">
                        <div class="search-area-inner">
                            <div class="search-contents ">
                                <h3 class="heading">Basic Information</h3>
                                <form method="post" action="/property">
                                    @include('form_partial.form')
                                    <div class="row">
                                        <div class="col-lg-6 col-4">
                                            <a href="{{url()->previous()}}" class="btn btn-link">
                                                <i class="fa fa-chevron-left"></i>
                                                Back
                                            </a>
                                        </div>
                                        <div class="col-lg-6 col-4">
                                            <button type="submit" class="text-white btn btn-md btn-color">Continue</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- User page end -->

    @include('partials.footer')

@endsection

resources/views/properties/edit.blade.php
@extends('layouts.app')

@section('content')


<!-- Sub banner 2 start -->

@include('partials.banner', ['title' => 'Edit Property', 'type' =>'Edit Property' ])

<!-- Sub banner 2 end -->

<!-- User page start -->
<div class="user-page content-area-7">
    <div class="container">
        <div class="row">
                <div class="search-area contact-1">
                    <div class="search-area-inner">
                        <div class="search-contents ">
                            <h3 class="heading">Basic Information</h3>
                              @if(Session::has('success'))
                                    <div class="alert alert-success">
                                        {{ Session::get('success') }}
                                    </div>
                            @endif
                            <form method="post" action="/property/{{$property->id}}">
                                @method('PATCH')
                                 @include('form_partial.form')
                               <div class="row">
                                <div class="col-lg-12">
                                    <button type="submit" class="btn btn-md btn-primary">Update Property</button>
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- User page end -->

@include('partials.footer')

@endsection

resources/views/properties/index.blade.php
@extends('layouts.app')

@section('content')

@include('partials.header')

<!-- Sub banner 2 start -->

@include('partials.banner', ['title' => 'Our Property', 'type' =>'Our Property' ])

<!-- Sub banner 2 end -->


<!-- Properties list rightside start -->
<div class="properties-list-rightside content-area-2">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12">
                <div class="option-bar d-none d-xl-block d-lg-block d-md-block d-sm-block">
                    <div class="row clearfix">
                        <div class="col-xl-4 col-lg-5 col-md-5 col-sm-5">
                            <h4>
                                <span class="heading-icon">
                                        <!-- <i class="fa fa-caret-right icon-design"></i>
                                        <i class="fa fa-th-large"></i> -->
                                </span>
                                <span class="heading">Properties</span>
                            </h4>
                        </div>

                        <div class="col-xl-8 col-lg-7 col-md-7 col-sm-7">
                            <div class="sorting-options clearfix">
                                <!-- <a href="properties-list-rightside.html" class="change-view-btn"><i class="fa fa-th-list"></i></a>
                                <a href="properties-grid-rightside.html" class="change-view-btn active-view-btn"><i class="fa fa-th-large"></i></a> -->
                            </div>
                            @if (count($properties))
                                <div class="search-area">
                                    <select class="selectpicker search-fields" name="location">
                                        <option>High to Low</option>
                                        <option>Low to High</option>
                                    </select>
                                </div>
                            @endif
                        </div>
                    </div>
                </div>
              <!--   <div class="subtitle">
                    20 Result Found
                </div> -->
                <div class="row">
                    @forelse($properties as $property)
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <div class="property-box">
                            <div class="property-thumbnail">
                                <a href="/property/{{$property->slug}}" class="property-img">
                                    <div class="tag button alt featured">Vacant</div>
                                    <div class="price-ratings-box">
                                        <p class="price">
                                            Ksh. {{ $property->price + $property->service_charge }}
                                        </p>
                                    </div>
                                    <x-image :property="$property" class="img=fluid"></x-image>
                                </a>
                            </div>
                            <div class="detail">
                                <h1 class="title">
                                    <a href="/property/{{$property->slug}}">{{$property->title}}</a>
                                </h1>
                                <div class="location">
                                    <a href="/property/{{$property->slug}}">
                                        <i class="fa fa-map-marker"></i>{{$property->street}}, {{$property->town}},
                                    </a>
                                </div>
                                <ul class="facilities-list clearfix">
                                    <li>
                                        <i class="flaticon-bed"></i>  {{$property->bedroom}} Bedrooms
                                    </li>
                                    <li>
                                        <i class="flaticon-bath"></i> {{$property->bathroom}} Bathrooms
                                    </li>
                                    <li>
                                        <i class="flaticon-square-layouting-with-black-square-in-east-area"></i> Sq Ft:{{$property->area}}
                                    </li>
                                  <!--   <li>
                                        <i class="flaticon-car-repair"></i> 1 Garage
                                    </li> -->
                                </ul>
                            </div>
                            <div class="footer">
                                <a href="#">
                                    <i class="fa fa-user"></i> {{$property->user->name}}
                                </a>
                                <span>
                                <i class="fa fa-calendar-o"></i> {{ $property->formatted_created_at}}
                            </span>
                            </div>
                        </div>
                    </div>
                    @empty
                    <h3 class="ml-4">No properties yet</h3>
                    @endforelse
                    <div class="col-lg-12">
                        <div class="pagination-box hidden-mb-45">
                            {{ $properties->links('partials.pagination') }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="sidebar mbl">
                    @if(count($properties) > 0)
                         @include('partials.sidebar')
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Properties list rightside end -->

@include('partials.footer')

@endsection

resources/views/properties/upload-photos.blade.php
@extends('layouts.app')

@section('content')

    @include('partials.header')

    <!-- Sub banner 2 start -->

    @include('partials.banner', ['title' => 'Upload Image', 'type' =>'Upload Property Image' ])

    <!-- Sub banner 2 end -->

    <!-- Sub banner 2 end -->
    <div class="container py-4">
        <div class="box">
            @foreach($property->photos->chunk(3) as $set)
                <div class="row">
                    @foreach($set as $photo)
                        <div class="col-md-4 col-lg-4 pt-4">
                            <form method="post" action="/photo/{{$photo->id}}">
                                @csrf
                                {{ method_field('DELETE')}}
                                <button type="submit" class="float-left -pl-4 btn btn-black">Delete</button>
                            </form>
                            <img src="/{{$photo->thumbnail_path}}">
                        </div>
                    @endforeach
                </div>
            @endforeach
        </div>
        <div class="box py-4">
            <h3 class="heading">Property Gallery</h3>
            <form id="myDropzone" action="/photo/{{$slug}}/files"
                  class="dropzone" method="post" enctype="multipart/form-data">
                @csrf
            </form>
        </div>
        @if ($errors->has('description'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('file') }}</strong>
            </span>
        @endif

        <div class="py-4">
            <div class="row">
                <div class="col-md-6">
                    <a href="javascript:history.back()" class="btn btn-info">Back</a>
                </div>
                <div class="col-md-6">
                    <a href="/property/{{$property->slug}}" class="btn btn-primary">Publish</a>
                </div>
            </div>
        </div>
    </div>

    @section('scripts.footer')
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js"></script>
        <script>
            Dropzone.options.myDropZone = {
                paramName: 'file',
                maxFilesize: 15.0,
                acceptedFiles: '.jpg,.jpeg,.png, .bmp, .webp'
            };
        </script>
    @stop
@endsection