routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



/**
 * Public Viewing Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('/','WelcomeController@index');
Route::view('about', 'about');
Route::view('services', 'services');
Route::view('my-favorite', 'tenant.my-favorite');
Route::view('faq', 'faq');


/**
 * Contact Us  Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('/contact-us', 'ContactsController@index');
Route::post('/contact-us', 'ContactsController@store');


// Route::view('blog','blog');

// Route::view('blog-details','blog-full');


/**
 * Password Reset Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('settings-password', 'SettingsController@index');
Route::patch('settings-password', 'SettingsController@update');

Route::get('my-properties', 'UserPropertiesController@index')->name('my-properties');


/**
 * Roles Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('role', 'RoleController@index');
Route::post('role', 'RoleController@store');

/**
 * Property Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('property', 'PropertyController@index');
Route::post('property', 'PropertyController@store');
Route::get('property/create', 'PropertyController@create');
Route::get('property/{id}/edit', 'PropertyController@edit');
Route::get('property/{slug}', 'PropertyController@show');
Route::patch('property/{slug}', 'PropertyController@update');
Route::delete('property/{id}', 'PropertyController@destroy');

/**
 * Property Photos Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::post('photo/{slug}/files', 'PropertyController@addPhoto');
Route::get('photo/{slug}', 'PropertyPhotoController@show');
Route::delete('photo/{slug}', 'PropertyPhotoController@destroy');


/**
 * Agents Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('agent', 'AgentProfileController');
Route::get('agent-settings', 'ProfilePictureController@index');


/**
 * Admin Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('admin', 'AdminController@index');
Route::get('all-admins', 'AdminController@allAdmins');
Route::get('admin/create', 'AdminController@create');
Route::post('admin/{admin}', 'AdminController@store');
Route::post('admin-profile', 'AdminProfileController@store');
Route::get('admin-properties', 'AdminAllPropertiesController');
Route::get('admin-settings', 'AdminSettingsController');
Route::post('admin-settings', 'AdminSettingsController@store');
Route::get('all-agents', 'AllAgentsController');
Route::get('all-tenants', 'AllTenantsController');
Route::get('all-landlords', 'AllLandlordController');
Route::get('list-blogs', 'AllBlogsController');

/**
 * LandLord Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('landlord', 'LandlordProfileController');
Route::get('landlord-settings', 'LandlordProfilePictureController@index');
Route::post('landlord-settings', 'LandlordProfilePictureController@store');
Route::get('/landlord-properties', 'LandLordPropertiesController@index');

/**
 * Tenants Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('tenant', 'TenantProfileController');
Route::get('tenant-settings', 'TenantProfilePictureController@index');


Route::get('my-tenants', 'RentedPropertyController@index');
Route::delete('/profile-picture/{id}', 'ProfilePictureController@destroy');
Route::post('/profile-picture', 'ProfilePictureController@store');

/**
 * Blog Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::resource('blogs', 'BlogController');
Route::get('blog/{slug}/images', 'BlogImageController@create')->middleware('admin');
Route::post('blog-images/{slug}/files', 'BlogController@addImage')->middleware('admin');
Route::delete('blog-image/{blog}/', 'BlogImageController@destroy')->middleware('admin');
Route::post('blog/{blog}/comments', 'BlogCommentsController@store');
Route::post('comments/{comment}/reply', 'CommentsReplyController@store')->middleware('admin');
Route::patch('comments/{comment}/reply', 'CommentsReplyController@update')->middleware('admin');
Route::get('comments/{comment}', 'CommentsReplyController@index');
Route::get('blog/show', 'BlogController@show'); // This is a temporary route




/**
 * Payment Routes Groups
 * ----------------------------------------------------------------------------------------->
 */
Route::get('payments', 'MyPaymentController@index');
Route::get('rental/{slug}', 'RentalController@index');
Route::post('tujenge', 'TujengepayController@savedata');
Route::get('wallet', 'WalletController@index');
Route::get('status', 'WalletController@status');
Route::post('wallet', 'WalletController@walletToMpesa');
Route::get('balance', 'WalletToBankController@balance');
Route::get('transaction-query', 'WalletController@transactionsQuery'); //Mpesa
Route::get('ministatement', 'MinistatementController@ministatement');
Route::get('wallet-to-bank', 'WalletToBankController@index');
Route::post('wallet-to-bank', 'WalletToBankController@walletToBank');
Route::get('transaction-query-bank', 'WalletToBankTransanctionQueryController@transactionBankQuery'); //Bank
Route::post('collection', 'CollectionController@interswitchCollection'); //collection
Route::get('card', 'CollectionController@card'); //collection



//password Ngi!956ozeh

/**
 * Socialite Authentication Routes
 * ----------------------------------------------------------------------------------------->
 */
Route::get('redirect/{provider}', 'SocialController@redirect');
Route::get('callback/{provider}', 'SocialController@callback');
Route::get('logout', 'Auth\LoginController@logout');

Auth::routes();

app/Blog.php
<?php

namespace App;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Blog extends Model
{
    use Sluggable, Uuids, HasFactory;

    protected $casts = ['id' => 'string'];

    protected $fillable = [
        'description',
        'title',
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function sluggable() :array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function path()
    {
        return '/blog/'.$this->slug;
    }

    public function photos()
    {
        return $this->hasMany(BlogImage::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function getFormattedTitleAttribute()
    {
        return Str::limit($this->title, 15);
    }

    public function formattedDate()
    {
        return $this->created_at->format('M d');
    }
    public function formattedDay()
    {
        return $this->created_at->format('d');
    }
    public function formattedMonth()
    {
        return $this->created_at->format('M');
    }

    public function blogDescription(): string
    {
        return Str::limit($this->description, 150, '..');
    }

    public function getExcerptAttribute(): string
    {
        return Str::limit($this->description, 75, '...');
    }


    public static function locatedAt($slug)
    {
        return static::where(compact('slug'))->firstOrFail();
    }

    public function addPhoto(BlogImage $blogImages)
    {
        return $this->photos()->save($blogImages);
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use App\BlogImage;
use App\Reply;
use Illuminate\Http\Request;
use App\Http\Requests\BlogRequest;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class BlogController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth')->except(['index', 'show']);
	}


	public function index()
	{
		$blogs = Blog::query()
		->select('id','title','description','slug','user_id','created_at')
		->with('user:id,name','photos:path,blog_id')->latest()->paginate(9);

		return view('blog.index', compact('blogs'));
	}


	public function create(Blog $blog)
	{
		return view('blog.create', compact('blog'));
	}


	public function store(Blog $blog, BlogRequest $request)
	{
		$blog = auth()->user()->blog()->create($request->all());

		return redirect($blog->path().'/images');

	}

	public function addImage(Request $request, $slug)
	{

		$this->validate($request, ['file' => 'required|mimes:jpg,jpeg,png,bmp']);

		$blogImage = $this->makePhoto($request->file('file'));

		Blog::locatedAt($slug)->addPhoto($blogImage);

	}

	protected function makePhoto(UploadedFile $file)
	{
		return BlogImage::named($file->getClientOriginalName())->move($file);
	}


	public function show(Blog $blog, Reply $reply)
	{
		$comments = $blog->comments->load('replies.user');
		return view('blog.show', compact('blog', 'comments', 'reply'));
	}


	public function edit(Blog $blog)
	{
		return view('blog.edit', compact('blog'));
	}

	public function update(BlogRequest $request, Blog $blog)
	{
		$blog = Blog::findOrFail($blog->id);

        $blog->update($request->all());

		return redirect($blog->path().'/images');
	}


	public function destroy(Blog $blog)
	{
		Blog::findOrFail($blog->id)->delete();

        return back()->with('deleted-blog', 'You have removed a blog listing');
	}
}

resources/views/blog/blog-images.blade.php
@extends('blog.main')

@section('details')

    <div class="sub-banner overview-bgi">
        <div class="container">
            <div class="breadcrumb-area">
                <h1>Blog Images</h1>
                <ul class="breadcrumbs">
                    <li><a href="/">Home</a></li>
                    <li class="active">Add an image</li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Sub banner 2 end -->
    <div class="container py-4">
        <div class="box">
            @foreach($blog->photos->chunk(3) as $set)
                <div class="row">
                    @foreach($set as $photo)
                        <div class="col-md-4 col-lg-4">
                            <form method="post" action="/blog-image/{{$photo->id}}" class="mb-0">
                                @csrf
                                {{ method_field('DELETE')}}
                                <div class="">
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </div>
                            </form>
                            <img src="/{{$photo->thumbnail}}" alt="">
                        </div>
                    @endforeach
                </div>
            @endforeach
        </div>
        <div class="box py-4">
            <h3 class="heading">Blog Gallery</h3>
            <form id="myDropzone" action="/blog-images/{{$slug}}/files"
                  class="dropzone" method="post" enctype="multipart/form-data">
                @csrf
            </form>
        </div>

        <div class="py-4">
            <div class="row flex-nowrap justify-content-between">
                <div class="col-md-6">
                    <a href="javascript:history.back()" class="btn btn-info">Back</a>
                </div>
                <div class="col-md-6 ">
                    <a href="/blogs/{{$blog->slug}}" class="btn btn-primary">Publish</a>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('scripts.footer')
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js"></script>
    <script>
        Dropzone.options.myDropZone = {
            paramName: 'file',
            maxFilesize: 10.0,
            acceptedFiles: '.jpg,.jpeg,.png, .bmp'
        };
    </script>
@stop

resources/views/blog/create.blade.php
@extends('blog.main')

@section('details')


<!-- Sub banner 2 start -->
@include('partials.banner', ['title' => 'Create Blog', 'type' => 'Add a blog' ])
    <!-- Sub banner 2 end -->

    <!-- User page start -->
    <div class="user-page content-area-7">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="search-area contact-1">
                        <div class="search-area-inner">
                            <div class="search-contents ">
                                <h3 class="heading">The Blog</h3>
                                <form method="post" action="/blogs">
                                    @include('form_partial.blog')
                                    <div class="row">
                                        <div class="col-lg-6 col-4">
                                            <a href="{{url()->previous()}}" class="btn btn-link">
                                                <i class="fa fa-chevron-left"></i>
                                                Back
                                            </a>
                                        </div>
                                        <div class="col-lg-6 col-4">
                                            <button type="submit" class="btn btn-md btn-primary">Continue</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- User page end -->

@endsection

resources/views/blog/edit.blade.php
@extends('blog.main')

@section('details')


    <!-- Sub banner 2 start -->
    @include('partials.banner', ['title' => 'Edit Blog', 'type' => 'Edit a blog' ])
    <!-- Sub banner 2 end -->

    <!-- User page start -->
    <div class="user-page content-area-7">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="search-area contact-1">
                        <div class="search-area-inner">
                            <div class="search-contents ">
                                <h3 class="heading">The Blog</h3>
                                <form method="post" action="{{ route('blogs.update', $blog) }}">
                                	@method('patch')
                                    @include('form_partial.blog')
                                    <div class="row">
                                        <div class="col-lg-6 col-4">
                                            <a href="{{url()->previous()}}" class="btn btn-link">
                                                <i class="fa fa-chevron-left"></i>
                                                Back
                                            </a>
                                        </div>
                                        <div class="col-lg-6 col-4">
                                            <button type="submit" class="btn btn-md btn-primary">Continue</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- User page end -->

@endsection

resources/views/blog/index.blade.php
@extends('blog.main')

@section('details')

<!-- Sub banner 2 start -->

@include('partials.banner', ['title' => 'Blog For Our Properties', 'type' =>'What Others are Saying' ])

<!-- Sub banner 2 end -->

<!-- Blog section start -->
<div class="blog-section content-area-2">
   <div class="container">
		<div class="row">
			@forelse ($blogs as $blog)
			<div class="col-lg-4 col-md-6 col-sm-6">
				<div class="blog-grid-box">
					@foreach($blog->photos->chunk(1) as $set)
					  @foreach($set as $photo)
                            @if ($loop->parent->first)
                            <img class="blog-theme img-fluid" src="/{{$photo->path}}" alt="blog-3">
                            @endif
                        @endforeach
                     @endforeach
					<div class="detail my-4">
						<div class="date-box">
							<h5>{{ $blog->formattedDay() }}</h5>
							<h5> {{ $blog->formattedMonth() }}</h5>
						</div>
						<h3>
							<a href="/blogs/{{ $blog->slug }}">{{ $blog->title }}</a>
						</h3>
						<div class="post-meta">
							<span><a href="#"><i class="fa fa-user"></i>{{ $blog->user->name }}</a></span>
							<span><a href="#"><i class="fa fa-commenting-o"></i>24 Comment</a></span>
						</div>
						<p style="height: 7rem">{{ $blog->blogDescription() }}</p>
						<a href="/blogs/{{ $blog->slug }}" class="btn-read-more">Read more</a>
					</div>
				</div>
			</div>
			@empty
			<div class="col-lg-12">
				<h3 class="heading">No blogs posted yet </h3>
			</div>
			@endforelse
            </div>
            <div class="col-lg-12">
            	<div class="pagination-box">
            		<nav aria-label="Page navigation example">
            			<ul class="pagination">
            				{{ $blogs->links() }}
            			</ul>
            		</nav>
            	</div>
          </div>
        </div>
    </div>
</div>
<!-- Blog section end -->

@endsection

resources/views/blog/main.blade.php
@extends('layouts.app')


@section('content')

    @include('partials.header')

       @yield('details')

    @include('partials.footer')
    
@endsection

resources/views/blog/show.blade.php
@extends('blog.main')

@section('details')


    <!-- Sub banner 2 start -->
    @include('partials.banner', ['title' => 'Blog in Full Details ', 'type' => 'Our Property Full Details' ])
    <!-- Sub banner 2 end -->

  <!-- Blog section start -->
<div class="blog-section content-area-7">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <!-- Blog grid box start -->
                <div class="blog-grid-box">
                    @foreach($blog->photos->chunk(1) as $set)
                        @foreach($set as $photo)
                            @if ($loop->parent->first)
                            <img class="blog-theme img-fluid" src="/{{$photo->path}}" alt="blog-3">
                            @endif
                        @endforeach
                    @endforeach
                    <div class="detail">
                        <div class="date-box">
                            <h5>{{ $blog->formattedDay() }}</h5>
                            <h5> {{ $blog->formattedMonth() }}</h5>
                        </div>
                        <h2>
                            {{ $blog->title }}
                        </h2>
                        <div class="post-meta">
                            <span><a href="#"><i class="fa fa-user"></i>{{ $blog->user->name }}</a></span>
                            <span><a><i class="fa fa-clock-o"></i>{{ $blog->formattedDate() }}</a></span>
                            <span><a href="#"><i class="fa fa-commenting-o"></i>24 Comment</a></span>
                        </div>
                        <p style="white-space: pre-line">
                            {{ $blog->description }}
                        </p>
                        <br>
                        <div class="row clearfix tags-socal-box">
                            <div class="col-lg-7 col-md-7 col-sm-7">
                                <div class="tags">
                                    <h2>Tags</h2>
                                    <ul>
                                        <li><a href="#">Image</a></li>
                                        <li><a href="#">Features</a></li>
                                        <li><a href="#">Gallery</a></li>
                                        <li><a href="#">News</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-5 col-md-5 col-sm-5">
                                <div class="social-list">
                                    <h2>Share</h2>
                                    <ul>
                                        <li>
                                            <a href="#" class="facebook">
                                                <i class="fa fa-facebook"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="twitter">
                                                <i class="fa fa-twitter"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="google">
                                                <i class="fa fa-google"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="linkedin">
                                                <i class="fa fa-linkedin"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="rss">
                                                <i class="fa fa-rss"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Blog grid box end -->
                <!-- Comments section start -->
              <comments-section :comments="{{ $comments }}" :blog="{{ $blog }}"></comments-section>
            </div>
        </div>
    </div>
</div>
<!-- Blog section end -->
@endsection